#define TRUE 1
#define FALSE 0

#define OK 0
#define EXISTS 1
#define ERROR 2

#define NEW 3
#define NOTAVOTER 4
#define ALREADYVOTED 5

//DEFINE STRINGS
#define STRING_OK	"OK"
#define STRING_EXISTS	"EXISTS"
#define STRING_ERROR	"ERROR"
#define STRING_TRUE	"TRUE"
#define STRING_FALSE	"FALSE"
#define STRING_NEW	"NEW"
#define STRING_NOTAVOTER	"NOTAVOTER"
#define STRING_ALREADYVOTED	"ALREADYVOTED"

